// Canciopnes y artistas incluídos
let allMusic = [

    {
        name: "Welcome to the Black Parade",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/Welcome_to_the_black_parade.mp3",
        fav:false,
    },
    {
        name: "Migraine",
        artist:"Twenty Øne Piløts",
        img: "images/migraine.png",
        audio:"audio/Migraine.mp3",
        fav:false,
    },
    {
        name: "Inmortales",
        artist:"Funzo & Baby Loud",
        img: "images/inmortales.jpg",
        audio:"audio/Inmortales.mp3",
        fav:false,
    },
    {
        name: "Youngblood",
        artist:"5 Seconds of Summer",
        img: "images/5-seconds-of-summer-youngblood.jpg.opdownload",
        audio:"audio/5SOS_Youngblood.mp3",
        fav:false,
    },
    {
        name: "Another One Bites the Dust",
        artist:"Queen",
        img: "images/queen_the_game.jpg",
        audio:"audio/Another_One_Bites_the_Dust.mp3",
        fav:false,
    },
    {
        name: "As It Was",
        artist:"Harry Styles",
        img: "images/as_it_was.png",
        audio:"audio/Harry_Styles_As_It_Was.mp3",
        fav:false,
    },
    {
        name: "Quevedo: Bzrp Music Session",
        artist:"Bzrp, Quevedo",
        img: "images/quevedo_music_session.jpg",
        audio:"audio/QUEVEDO_BZRP_Music_Sessions_52.mp3",
        fav:false,
    },
    {
        name: "Tití me preguntó",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/titi_me_pregunto.mp3",
        fav:false,
    },
    {
        name: "Me Porto Bonito",
        artist:"Bad Bunny ft. Chencho Corleone",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Me_Porto_Bonito_(ft._Chencho_Corleone).mp3",
        fav:false,

    },
    {
        name: "Mary on a cross",
        artist:"Ghost",
        img: "images/mary_on_a_cross.jpg",
        audio:"audio/Ghost_Mary_on_a_cross.mp3",
        fav:false,
    },
    {
        name: "Ojitos Lindos",
        artist:"Bad Bunny ft. Bomba Estéreo",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Ojitos_lindos.mp3",
        fav:false,
    },
    {
        name: "Chicken Teriyaki",
        artist:"Rosalía",
        img: "images/motomami.jpg",
        audio:"audio/ROSALÍA_CHICKEN_TERIYAKI.mp3",
        fav:false,
    },
    {
        name: "Seven",
        artist:"Natalie Jane",
        img: "images/seven.jpg",
        audio:"audio/natalie-jane-seven.mp3",
        fav:false,
    },
    {
        name: "Saoko",
        artist:"Rosalía",
        img: "images/motomami.jpg",
        audio:"audio/ROSALÍA_SAOKO.mp3",
        fav:false,
    },
    {
        name: "Memories",
        artist:"Conan Gray",
        img: "images/SUPERACHE.jfif",
        audio:"audio/conan-gray-memories.mp3",
        fav:false,
    },
    {
        name: "Perfect",
        artist:"One Direction",
        img: "images/made_in_the_am.jpg",
        audio:"audio/1D-Perfect.mp3",
        fav:false,
    },
    {
        name: "Romance",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
    },
    {
        name: "Honey, this mirror isn't big enough for the two of us",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
    },
    {
        name: "Vampires will never hurt you",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
     },{
        name: "Drowning lessons",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Our Lady of Sorrows",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
     },{
        name: "Headfirst for halos",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Skylines and turnstiles",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
     },{
        name: "Early sunsets over Monroeville",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/Early_Sunsets_Over_Monroeville",
        fav:false,
     },{
        name: "This is the best day ever",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Cubicles",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Demolition Lovers",
        artist:"My Chemical Romance",
        img: "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Helena",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/Helena.mp3",
        fav:false,
    },{
        name: "Give 'em hell, kid",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "To the end",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/to_the_end.mp3",
        fav:false,
    },{
        name: "You know what they do to guys like us in prison",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "I'm not okay (I promise)",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/not_okay",
        fav:false,
    },{
        name: "The ghost of you",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The jetset life is gonna kill you",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Interlude",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Thank you for the venom",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/thank_you_for_the_venom.mp3",
        fav:false,
    },{
        name: "Hang 'em high",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "It's not a fashion statement, it's a fucking deathwish",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Cemetery drive",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "I never told you what I do for a living",
        artist:"My Chemical Romance",
        img: "images/three_cheers.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The end",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Dead!",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/Dead!.mp3",
        fav:false,
    },{
        name: "This is how I disappear",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The sharpest lives",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "I don't love you",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/i_dont_love_you.mp3",
        fav:false,
    },{
        name: "House of wolves",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Cancer",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/Cancer.mp3",
        fav:false,
    },{
        name: "Mama",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Sleep",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/Mama_MCR.mp3",
        fav:false,
    },{
        name: "Teenagers",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/Teenagers.mp3",
        fav:false,
    },{
        name: "Disenchanted",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/Disenchanted.mp3",
        fav:false,
    },{
        name: "Famous last words",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/famous_last_words.mp3",
        fav:false,
    },{
        name: "Blood",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Heaven help us",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "My way home is through you",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Kill all your friends",
        artist:"My Chemical Romance",
        img: "images/black_parade.jpg",
        audio:"audio/kill_all_your_friends.mp3",
        fav:false,
    },{
        name: "Look alive, sunshine",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Na na na (na na na na na na na na na)",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/Na_Na_Na.mp3",
        fav:false,
    },{
        name: "Bulletproof heart",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "SING",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Planetary (GO!)",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/planetary_go.mp3",
        fav:false,
    },{
        name: "The only hope for me is you",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Jet-Star and the Kobra Kid/traffic report",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Party Poison",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Save yourself, I'll hold them back",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "S/C/A/R/E/C/R/O/W",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Summertime",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/Summertime.mp3",
        fav:false,
    },{
        name: "DESTROYA",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "The kids from yesterday",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Goodnite, Dr. Death",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Vampire money",
        artist:"My Chemical Romance",
        img: "images/danger_days.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Boy Division",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Tomorrow's Money",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "AMBULANCE",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Gun",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The World Is Ugly",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The Light Behind Your Eyes ",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Kiss the Ring",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Make Room!!!!",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Surrender the Night",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Burn Bright",
        artist:"My Chemical Romance",
        img: "images/Mychemconvweap.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Estamos bien",
        artist:"Bad Bunny",
        img: "images/X100pre.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Mía",
        artist:"Bad Bunny",
        img: "images/X100pre.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Solo de mi",
        artist:"Bad Bunny",
        img: "images/X100pre.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Caro",
        artist:"Bad Bunny",
        img: "images/X100pre.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Si estuviésemos juntos",
        artist:"Bad Bunny",
        img: "images/X100pre.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "La Romana",
        artist:"Bad Bunny",
        img: "images/X100pre.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Si Veo a Tu Mamá",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "La Difícil",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Pero Ya No",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "La Santa",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/La_Santa.mp3",
        fav:false,
    },{
        name: "Yo Perreo Sola",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/Yo_perreo_sola.mp3",
        fav:false,
    },{
        name: "Bichiyal",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Soliá",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/BAD_BUNNY_SOLIA.mp3",
        fav:false,
    },{
        name: "La Zona",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Que Malo",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Vete",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Ignorantes",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/ignorantes.mp3",
        fav:false,
    },{
        name: "A Tu Merced",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Una Vez",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Safaera",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "25/8",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Está Cabrón Ser Yo",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Puesto Pa' Guerrial",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "P FKN R",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Hablamos Mañana",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "<3",
        artist:"Bad Bunny",
        img: "images/YHLQMDLG.jfif",
        audio:"audio/",
        fav:false,
    },{
        name: "Te Mudaste",
        artist:"Bad Bunny",
        img: "images/El_Ultimo_Tour_del_Mundo.png",
        audio:"audio/BB_TE_MUDASTE.mp3",
        fav:false,
    },{
        name: "La Noche de Anoche",
        artist:"Bad Bunny Ft. ROSALÍA",
        img: "images/El_Ultimo_Tour_del_Mundo.png",
        audio:"audio/la_noche_de_anoche.mp3",
        fav:false,
    },{
        name: "Yo Visto Así",
        artist:"Bad Bunny",
        img: "images/El_Ultimo_Tour_del_Mundo.png",
        audio:"audio/Yo_visto_asi.mp3",
        fav:false,
    },{
        name: "Dakiti",
        artist:"Bad Bunny ft. Jhay Cortez",
        img: "images/El_Ultimo_Tour_del_Mundo.png",
        audio:"audio/Dakiti.mp3",
        fav:false,
    },{
        name: "120",
        artist:"Bad Bunny",
        img: "images/El_Ultimo_Tour_del_Mundo.png",
        audio:"audio/120_BB.mp3",
        fav:false,
    },{
        name: "Antes que se acabe",
        artist:"Bad Bunny",
        img: "images/El_Ultimo_Tour_del_Mundo.png",
        audio:"audio/ANTES_QUE_SE_ACABE.mp3",
        fav:false,
    },{
        name: "Canción Con Yandel",
        artist:"Bad Bunny ft. Yandel",
        img: "images/las-que-no-iban-a-salir.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Pa’ Romperla",
        artist:"Bad Bunny ft. Don Omar",
        img: "images/las-que-no-iban-a-salir.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Moscow Mule",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Moscow_Mule_BB.mp3",
        fav:false,
    },{
        name: "Después de la playa",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/despues_de_la_playa_bb.mp3",
        fav:false,
    },{
        name: "Un ratito",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Un_Ratito_BB.mp3",
        fav:false,
    },{
        name: "Yo no soy celoso",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Yo_no_soy_celoso_BB.mp3",
        fav:false,
    },{
        name: "Tarot",
        artist:"Bad Bunny ft. Jhay Cortez",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Tarot_BB.mp3",
        fav:false,
    },{
        name: "Neverita",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Nevertita_BB.mp3",
        fav:false,
    },{
        name: "La corriente",
        artist:"Bad Bunny ft. Tony Dize",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Corriente_BB.mp3",
        fav:false,
    },{
        name: "Efecto ",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Efecto.mp3",
        fav:false,
    },{
        name: "Party",
        artist:"Bad Bunny ft. Rauw Alejandro",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Party.mp3",
        fav:false,
    },{
        name: "Aguacero",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Aguacero.mp3",
        fav:false,
    },{
        name: "Enséñame a bailar",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Enséñame_a_Bailar.mp3",
        fav:false,
    },{
        name: "Dos mil 16",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/DosMil16_BB.mp3",
        fav:false,
    },{
        name: "El apagón",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/el_apagon.mp3",
        fav:false,
    },{
        name: "Otro atardecer",
        artist:"Bad Bunny ft. the Marías",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Otro_Atardecer.mp3",
        fav:false,
    },{
        name: "Un coco",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Un_Coco.mp3",
        fav:false,
    },{
        name: "Andrea",
        artist:"Bad Bunny ft. Buscabulla",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Andrea.mp3",
        fav:false,
    },{
        name: "Me fui de vacaciones",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Me_Fui_de_Vacaciones.mp3",
        fav:false,
    },{
        name: "Un verano sin ti",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/un_verano_sin_ti_bb.mp3",
        fav:false,
    },{
        name: "Agosto",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Bad_Bunny_Agosto.mp3",
        fav:false,
    },{
        name: "Callaíta",
        artist:"Bad Bunny",
        img: "images/un_verano_sin_ti.jfif",
        audio:"audio/Calladita_bb.mp3",
        fav:false,
    },{
        name: "Soltera (Remix)",
        artist:"Bad Bunny ft. Daddy Yankee & Lunay",
        img: "images/epico.jpg",
        audio:"audio/soltera_remix.mp3",
        fav:false,
    },{
        name: "Tú no vive así",
        artist:"Arcangel x Bad Bunny X Dj Luian X Mambo Kingz",
        img: "images/tu_no_vive_asi.jpg",
        audio:"audio/tu_no_vive_asi.mp3",
        fav:false,
    },{
        name: "Yonaguni",
        artist:"Bad Bunny",
        img: "images/yonaguni.png",
        audio:"audio/Yonaguni.mp3",
        fav:false,
    },{
        name: "Raised by Wolves",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Tragic Magic",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The Drug in Me Is You",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "I'm Not a Vampire",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Good Girls Bad Guys",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Pick Up the Phone",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Don't Mess With Ouija Boards",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Sink or Swim",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Caught Like a Fly ",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Goodbye Graceful",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The Westerner",
        artist:"Falling In Reverse",
        img: "images/The_Drug_in_Me_Is_You.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Champion",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Bad Girls Club",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/FALLING_IN_REVERSE_Bad_Girls_Club.mp3",
        fav:false,
    },{
        name: "Rolling Stone",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Fashionably Late",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Alone",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Born to Lead",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "It's Over When It's Over",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Game Over",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Self-Destruct Personality",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Fuck the Rest",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Keep Holding On",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Drifter",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Where Have You Been",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Goddamn",
        artist:"Falling In Reverse",
        img: "images/fashionably_late.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Chemical Prisoner",
        artist:"Falling In Reverse",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "God, If You Are Above...",
        artist:"Falling In Reverse",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Sexy Drug",
        artist:"Falling In Reverse",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Just Like You",
        artist:"Falling In Reverse",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Guillotine IV (The Final Chapter)",
        artist:"Falling In Reverse, Massabo, Jacky Vincent",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Stay Away",
        artist:"Falling In Reverse, Baskette, Thomas Denny",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Wait and See",
        artist:"Falling In Reverse, Massabo",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The Bitter End",
        artist:"Falling In Reverse",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "My Heart's To Blame",
        artist:"Falling In Reverse, Massabo",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Get Me Out",
        artist:"Falling In Reverse",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Die For You",
        artist:"Falling In Reverse",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Brother",
        artist:"Falling In Reverse",
        img: "images/just_like_you.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Coming Home",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Broken",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Loser",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Fuck You and All Your Friends",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "I Hate Everyone",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "I'm Bad at Life",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Hanging On",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Superhero",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Straight to Hell",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "I Don't Mind",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The Departure",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Right Now",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Paparazzi",
        artist:"Falling In Reverse",
        img: "images/coming_home.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Him & I",
        artist:"G-Eazy, Halsey",
        img: "images/beautiful&damned.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Walls Could Talk",
        artist:"Halsey",
        img: "images/Hopeless_Fountain_Kingdom.png",
        audio:"audio/",
        fav:false,
    },{
        name: "Control",
        artist:"Halsey",
        img: "images/Badlands.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "You Should Be Sad",
        artist:"Halsey",
        img: "images/Manic.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Without Me",
        artist:"Halsey",
        img: "images/without_me.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Gasoline",
        artist:"Halsey",
        img: "images/Badlands.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Colors",
        artist:"Halsey",
        img: "images/Badlands.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Nightmare",
        artist:"Halsey",
        img: "images/If_I_Can't_Have_Love,_I_Want_Power_by_Halsey.png",
        audio:"audio/",
        fav:false,
    },{
        name: "11 Minutes",
        artist:"Yungblud, Halsey",
        img: "images/11minutes.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "3 am",
        artist:"Halsey",
        img: "images/Manic.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Hurricane",
        artist:"Halsey",
        img: "images/Badlands.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Sorry",
        artist:"Halsey",
        img: "images/Hopeless_Fountain_Kingdom.png",
        audio:"audio/",
        fav:false,
    },{
        name: "We Will Rock You",
        artist:"Queen",
        img: "images/news_of_the_world.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Bohemian Rhapsody",
        artist:"Queen",
        img: "images/night_at_the_opera.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Don't Stop Me Now",
        artist:"Queen",
        img: "images/Queen_Jazz.png",
        audio:"audio/",
        fav:false,
    },{
        name: "I Want to Break Free",
        artist:"Queen",
        img: "images/made_in_heaven.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Killer Queen",
        artist:"Queen",
        img: "images/sheer_heart_attack.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Love of My Life",
        artist:"Queen",
        img: "images/night_at_the_opera.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Radio Ga Ga",
        artist:"Queen",
        img: "images/works.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "The Show Must Go On",
        artist:"Queen",
        img: "images/innuendo.jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "Somebody to Love",
        artist:"Queen",
        img: "images/A_Day_at_the_Races_(Queen).jpg",
        audio:"audio/",
        fav:false,
    },{
        name: "We Are the Champions",
        artist:"Queen",
        img: "images/news_of_the_world.jpg",
        audio:"audio/",
        fav:false,
    }
]

let allArtistas = [

    {
        perfil: "images/artist_profile/mcr.jpg",
        foto_fondo: "images/banner/mcr.jpg",
        name: "My Chemical Romance",
        albumes: ["Three Cheers for Sweet Revenge", "Black Parade", "Danger Days: The True Lives of the Fabulous Killjoys",
            "I Brought You My Bullets, You Brought Me Your Love", "Conventional Weapons"],
        albumes_foto:["images/three_cheers.jpg", "images/black_parade.jpg", "images/danger_days.jfif",
            "images/I_Brought_You_My_Bullets,_You_Brought_Me_Your_Love_cover.jpg", "images/Mychemconvweap.jpg"],
        index:1,

    },
    {
        perfil: "images/artist_profile/top.png",
        foto_fondo: "images/banner/twenty-one-pilots.jpg",
        name: "Twenty Øne Piløts",
        albumes: ["Blurryface", "Scaled and Icy", "Twenty One Pilots", "Trench", "Vessel", "Regional att Best"],
        albumes_foto:["images/blurryface.jpg", "images/scaled.jpg", "images/top.jpg", "images/trench.jpg",
            "images/migraine.png", "images/twenty-one-pilots-regional-at-best.jpg"],
        index:2,

    },
    {
        perfil: "images/artist_profile/bad_bunny.jpg",
        foto_fondo: "images/banner/un_verano_sin_ti.jpg",
        name: "Bad Bunny",
        albumes: ["Un verano sin ti", "YHLQMDLG", "El último tour del mundo", "X 100pre", "Oasis", "El Conejo Malo",
            "Las que no iban a salir"],
        albumes_foto:["images/un_verano_sin_ti.jfif","images/YHLQMDLG.jfif", "images/El_Ultimo_Tour_del_Mundo.png",
            "images/X100pre.jpg", "images/oasis.jfif", "images/elconejomalo.jfif", "images/las-que-no-iban-a-salir.jpg"],
        index:3,
    },
    {
        perfil: "images/artist_profile/5sos.jpg",
        foto_fondo: "images/banner/5sos.jpg",
        name: "5 Seconds of Summer",
        albumes: ["5 Seconds of Summer", "Sounds Good Feels Good", "Youngblood", "Calm", "5SOS5", "5 Seconds of Summer (B-Sides and Rarities)"],
        albumes_foto:["images/5_Seconds_of_Summer.jpg", "images/Sounds_Good_Feels_Good.png", "images/5-seconds-of-summer-youngblood.jpg.opdownload",
            "images/5_Seconds_of_Summer_Calm.png", "images/5_Seconds_of_Summer_-_5SOS5.png", "images/b_side.jfif"],
        index:4,

    },
    {
        perfil: "images/artist_profile/queen.jpg",
        foto_fondo: "images/banner/queen.jpg",
        name: "Queen",
        albumes: ["Queen", "Queen II", "A Night at the Opera", "News of the World", "The Miracle", "Jazz", "Hot Space",
            "Innuendo", "Made in Heaven", "A Day at the Races", "A Kind of Magic", "The Works", "Sheer Heart Attack",
            "The Game", "Live Killers", "Live Magic", "Queen at the Beeb"],
        albumes_foto:["images/LP_Label_Queen.jpg", "images/QueenII.webp", "images/night_at_the_opera.jpg", "images/news_of_the_world.jpg",
            "images/the_miracle.jpg","images/Queen_Jazz.png", "images/hot_space.jpg", "images/innuendo.jpg", "images/made_in_heaven.jpg",
            "images/A_Day_at_the_Races_(Queen).jpg", "images/kind_of_magic.jpg", "images/works.jpg", "images/sheer_heart_attack.jpg",
            "images/The_Game.webp", "images/liveKillers.jpg", "images/live_magic.jpg", "images/Queen_At_The_Beeb.png"],
        index:5,

    },
    {
        perfil: "images/artist_profile/harry_styles.jfif",
        foto_fondo: "images/banner/harry_styles.jpg",
        name: "Harry Styles",
        albumes: ["Harry's House", "Harry Styles", "Fine Line"],
        albumes_foto:["images/harrys_house.jpg", "images/artist_profile/harry_styles.jfif", "images/Harry_Styles_Fine_Line.png"],
        index:6,

    },
    {
        perfil: "images/artist_profile/falling_in_reverse.jfif",
        foto_fondo: "images/banner/falling-in-reverse.jpg",
        name: "Falling In Reverse",
        albumes: ["The Drug In Me Is You", "Fashionably Late", "Just Like You", "Coming Home"],
        albumes_foto:["images/The_Drug_in_Me_Is_You.jpg", "images/fashionably_late.png", "images/just_like_you.jpg", "images/coming_home.jpg"],
        index:7,

    },
    {
        perfil: "images/artist_profile/quevedo.jpg",
        foto_fondo: "images/banner/quevedo.jpg",
        name: "Quevedo",
        albumes: [],
        albumes_foto:[],
        index:8,


    },
    {
        perfil: "images/artist_profile/bizarrap.jpg",
        foto_fondo: "images/banner/bizarrap.jpg",
        name: "Bizarrap",
        albumes: [],
        albumes_foto:[],
        index:9,

    },
    {
        perfil: "images/artist_profile/halsey.jfif",
        foto_fondo: "images/banner/halsey.jpg",
        name: "Halsey",
        albumes: ["If I Can't Have Love, I Want Power", "Manic", "Badlands", "Hopeless Fountain Kingdom"],
        albumes_foto:["images/If_I_Can't_Have_Love,_I_Want_Power_by_Halsey.png", "images/Manic.jpg",
            "images/BADLANDS.jpg", "images/Hopeless_Fountain_Kingdom.png"],
        index:10,

    },
    {
        perfil: "images/artist_profile/rosalia.jfif",
        foto_fondo: "images/banner/Rosalia.jpg",
        name: "Rosalía",
        albumes: ["El mal querer", "Motomami", "Los ángeles"],
        albumes_foto:["images/mal_querer.jfif","images/motomami.jpg","images/los_angeles.jpg"],
        index:11,

    },
    {
        perfil: "images/artist_profile/conan_gray.jfif",
        foto_fondo: "images/banner/conan_gray.jpg",
        name: "Conan Gray",
        albumes: ["Sunset Season", "Kid Krow", "Superache"],
        albumes_foto:["images/Sunset_Season.jpg","images/Kid_Krow.jpg","images/SUPERACHE.jfif"],
        index:12,

    },
    {
        perfil: "images/artist_profile/natalie_jane.jfif",
        foto_fondo: "images/banner/natalie_jane.jpg",
        name: "Natalie Jane",
        albumes: [],
        albumes_foto:[],
        index:13,

    },

    {
        perfil: "images/artist_profile/ghost.jfif",
        foto_fondo: "images/banner/ghost.jpg",
        name: "Ghost B.C,",
        albumes: ["Impera", "Prequelle", "Meliora", "Infestissum", "Opus Eponymous", "Ceremony and Devotion",
            "[MESSAGE FROM THE CLERGY]", "Seven Inches of Satanic Panic"],
        albumes_foto:["images/imperia.jpg", "images/meliora.jpg", "images/infestissumam.jpg", "images/infestissumam.jpg",
            "images/opus_eponymous.jpg", "images/ceremony_and_devotion.jpg",
            "images/ghost-message-from-the-clergy-Cover-Art.jpg", "images/mary_on_a_cross.jpg"],
        index:14,

    }
]

